#theme: jekyll-theme-architect
theme: jekyll-theme-leap-day

title: So You Wanna Code

description: Andrew's suggestions for learning how to code

permalink: /:year/:month/:day/:title:output_ext

plugins:
  - jekyll-feed
